name: tests-cov
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
            - name: chekout repo
              uses: actions/checkout@v2
            - name: setup python
              uses: actions/setup-python@v2
            - name: Install dependencies
              run: |
                  pip install poetry
                  make install
                  pip install pytest
                  pip install pytest-cov
            - name: codeclimate upload
              uses: paambaati/codeclimate-action@v3.0.0
              env:
                CC_TEST_REPORTER_ID: ${{secrets.cov}}
              with:
                coverageCommand: make coverage
                debug: true
